/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fun.playinfo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FileTypeVO implements org.apache.thrift.TBase<FileTypeVO, FileTypeVO._Fields>, java.io.Serializable, Cloneable, Comparable<FileTypeVO> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FileTypeVO");

  private static final org.apache.thrift.protocol.TField FILE_TYPE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("fileTypeID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("fileCode", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField FILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("fileName", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FileTypeVOStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FileTypeVOTupleSchemeFactory());
  }

  public int fileTypeID; // required
  public String fileCode; // required
  public String fileName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILE_TYPE_ID((short)1, "fileTypeID"),
    FILE_CODE((short)2, "fileCode"),
    FILE_NAME((short)3, "fileName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_TYPE_ID
          return FILE_TYPE_ID;
        case 2: // FILE_CODE
          return FILE_CODE;
        case 3: // FILE_NAME
          return FILE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FILETYPEID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_TYPE_ID, new org.apache.thrift.meta_data.FieldMetaData("fileTypeID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FILE_CODE, new org.apache.thrift.meta_data.FieldMetaData("fileCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("fileName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FileTypeVO.class, metaDataMap);
  }

  public FileTypeVO() {
  }

  public FileTypeVO(
    int fileTypeID,
    String fileCode,
    String fileName)
  {
    this();
    this.fileTypeID = fileTypeID;
    setFileTypeIDIsSet(true);
    this.fileCode = fileCode;
    this.fileName = fileName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FileTypeVO(FileTypeVO other) {
    __isset_bitfield = other.__isset_bitfield;
    this.fileTypeID = other.fileTypeID;
    if (other.isSetFileCode()) {
      this.fileCode = other.fileCode;
    }
    if (other.isSetFileName()) {
      this.fileName = other.fileName;
    }
  }

  public FileTypeVO deepCopy() {
    return new FileTypeVO(this);
  }

  @Override
  public void clear() {
    setFileTypeIDIsSet(false);
    this.fileTypeID = 0;
    this.fileCode = null;
    this.fileName = null;
  }

  public int getFileTypeID() {
    return this.fileTypeID;
  }

  public FileTypeVO setFileTypeID(int fileTypeID) {
    this.fileTypeID = fileTypeID;
    setFileTypeIDIsSet(true);
    return this;
  }

  public void unsetFileTypeID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FILETYPEID_ISSET_ID);
  }

  /** Returns true if field fileTypeID is set (has been assigned a value) and false otherwise */
  public boolean isSetFileTypeID() {
    return EncodingUtils.testBit(__isset_bitfield, __FILETYPEID_ISSET_ID);
  }

  public void setFileTypeIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FILETYPEID_ISSET_ID, value);
  }

  public String getFileCode() {
    return this.fileCode;
  }

  public FileTypeVO setFileCode(String fileCode) {
    this.fileCode = fileCode;
    return this;
  }

  public void unsetFileCode() {
    this.fileCode = null;
  }

  /** Returns true if field fileCode is set (has been assigned a value) and false otherwise */
  public boolean isSetFileCode() {
    return this.fileCode != null;
  }

  public void setFileCodeIsSet(boolean value) {
    if (!value) {
      this.fileCode = null;
    }
  }

  public String getFileName() {
    return this.fileName;
  }

  public FileTypeVO setFileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

  public void unsetFileName() {
    this.fileName = null;
  }

  /** Returns true if field fileName is set (has been assigned a value) and false otherwise */
  public boolean isSetFileName() {
    return this.fileName != null;
  }

  public void setFileNameIsSet(boolean value) {
    if (!value) {
      this.fileName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_TYPE_ID:
      if (value == null) {
        unsetFileTypeID();
      } else {
        setFileTypeID((Integer)value);
      }
      break;

    case FILE_CODE:
      if (value == null) {
        unsetFileCode();
      } else {
        setFileCode((String)value);
      }
      break;

    case FILE_NAME:
      if (value == null) {
        unsetFileName();
      } else {
        setFileName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_TYPE_ID:
      return Integer.valueOf(getFileTypeID());

    case FILE_CODE:
      return getFileCode();

    case FILE_NAME:
      return getFileName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_TYPE_ID:
      return isSetFileTypeID();
    case FILE_CODE:
      return isSetFileCode();
    case FILE_NAME:
      return isSetFileName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FileTypeVO)
      return this.equals((FileTypeVO)that);
    return false;
  }

  public boolean equals(FileTypeVO that) {
    if (that == null)
      return false;

    boolean this_present_fileTypeID = true;
    boolean that_present_fileTypeID = true;
    if (this_present_fileTypeID || that_present_fileTypeID) {
      if (!(this_present_fileTypeID && that_present_fileTypeID))
        return false;
      if (this.fileTypeID != that.fileTypeID)
        return false;
    }

    boolean this_present_fileCode = true && this.isSetFileCode();
    boolean that_present_fileCode = true && that.isSetFileCode();
    if (this_present_fileCode || that_present_fileCode) {
      if (!(this_present_fileCode && that_present_fileCode))
        return false;
      if (!this.fileCode.equals(that.fileCode))
        return false;
    }

    boolean this_present_fileName = true && this.isSetFileName();
    boolean that_present_fileName = true && that.isSetFileName();
    if (this_present_fileName || that_present_fileName) {
      if (!(this_present_fileName && that_present_fileName))
        return false;
      if (!this.fileName.equals(that.fileName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(FileTypeVO other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileTypeID()).compareTo(other.isSetFileTypeID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileTypeID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileTypeID, other.fileTypeID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFileCode()).compareTo(other.isSetFileCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileCode, other.fileCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFileName()).compareTo(other.isSetFileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileName, other.fileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FileTypeVO(");
    boolean first = true;

    sb.append("fileTypeID:");
    sb.append(this.fileTypeID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fileCode:");
    if (this.fileCode == null) {
      sb.append("null");
    } else {
      sb.append(this.fileCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fileName:");
    if (this.fileName == null) {
      sb.append("null");
    } else {
      sb.append(this.fileName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FileTypeVOStandardSchemeFactory implements SchemeFactory {
    public FileTypeVOStandardScheme getScheme() {
      return new FileTypeVOStandardScheme();
    }
  }

  private static class FileTypeVOStandardScheme extends StandardScheme<FileTypeVO> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FileTypeVO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_TYPE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.fileTypeID = iprot.readI32();
              struct.setFileTypeIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileCode = iprot.readString();
              struct.setFileCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileName = iprot.readString();
              struct.setFileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FileTypeVO struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(FILE_TYPE_ID_FIELD_DESC);
      oprot.writeI32(struct.fileTypeID);
      oprot.writeFieldEnd();
      if (struct.fileCode != null) {
        oprot.writeFieldBegin(FILE_CODE_FIELD_DESC);
        oprot.writeString(struct.fileCode);
        oprot.writeFieldEnd();
      }
      if (struct.fileName != null) {
        oprot.writeFieldBegin(FILE_NAME_FIELD_DESC);
        oprot.writeString(struct.fileName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FileTypeVOTupleSchemeFactory implements SchemeFactory {
    public FileTypeVOTupleScheme getScheme() {
      return new FileTypeVOTupleScheme();
    }
  }

  private static class FileTypeVOTupleScheme extends TupleScheme<FileTypeVO> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FileTypeVO struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFileTypeID()) {
        optionals.set(0);
      }
      if (struct.isSetFileCode()) {
        optionals.set(1);
      }
      if (struct.isSetFileName()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetFileTypeID()) {
        oprot.writeI32(struct.fileTypeID);
      }
      if (struct.isSetFileCode()) {
        oprot.writeString(struct.fileCode);
      }
      if (struct.isSetFileName()) {
        oprot.writeString(struct.fileName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FileTypeVO struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.fileTypeID = iprot.readI32();
        struct.setFileTypeIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.fileCode = iprot.readString();
        struct.setFileCodeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.fileName = iprot.readString();
        struct.setFileNameIsSet(true);
      }
    }
  }

}

