/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fun.playinfo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PlayInfo implements org.apache.thrift.TBase<PlayInfo, PlayInfo._Fields>, java.io.Serializable, Cloneable, Comparable<PlayInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PlayInfo");

  private static final org.apache.thrift.protocol.TField PLAYINFO_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("playinfoId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField HASH_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("hashId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("msg", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PlayInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PlayInfoTupleSchemeFactory());
  }

  public int playinfoId; // required
  public String hashId; // required
  public boolean success; // required
  public String msg; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLAYINFO_ID((short)1, "playinfoId"),
    HASH_ID((short)2, "hashId"),
    SUCCESS((short)3, "success"),
    MSG((short)4, "msg");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLAYINFO_ID
          return PLAYINFO_ID;
        case 2: // HASH_ID
          return HASH_ID;
        case 3: // SUCCESS
          return SUCCESS;
        case 4: // MSG
          return MSG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PLAYINFOID_ISSET_ID = 0;
  private static final int __SUCCESS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAYINFO_ID, new org.apache.thrift.meta_data.FieldMetaData("playinfoId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HASH_ID, new org.apache.thrift.meta_data.FieldMetaData("hashId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.MSG, new org.apache.thrift.meta_data.FieldMetaData("msg", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PlayInfo.class, metaDataMap);
  }

  public PlayInfo() {
  }

  public PlayInfo(
    int playinfoId,
    String hashId,
    boolean success,
    String msg)
  {
    this();
    this.playinfoId = playinfoId;
    setPlayinfoIdIsSet(true);
    this.hashId = hashId;
    this.success = success;
    setSuccessIsSet(true);
    this.msg = msg;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PlayInfo(PlayInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.playinfoId = other.playinfoId;
    if (other.isSetHashId()) {
      this.hashId = other.hashId;
    }
    this.success = other.success;
    if (other.isSetMsg()) {
      this.msg = other.msg;
    }
  }

  public PlayInfo deepCopy() {
    return new PlayInfo(this);
  }

  @Override
  public void clear() {
    setPlayinfoIdIsSet(false);
    this.playinfoId = 0;
    this.hashId = null;
    setSuccessIsSet(false);
    this.success = false;
    this.msg = null;
  }

  public int getPlayinfoId() {
    return this.playinfoId;
  }

  public PlayInfo setPlayinfoId(int playinfoId) {
    this.playinfoId = playinfoId;
    setPlayinfoIdIsSet(true);
    return this;
  }

  public void unsetPlayinfoId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PLAYINFOID_ISSET_ID);
  }

  /** Returns true if field playinfoId is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayinfoId() {
    return EncodingUtils.testBit(__isset_bitfield, __PLAYINFOID_ISSET_ID);
  }

  public void setPlayinfoIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PLAYINFOID_ISSET_ID, value);
  }

  public String getHashId() {
    return this.hashId;
  }

  public PlayInfo setHashId(String hashId) {
    this.hashId = hashId;
    return this;
  }

  public void unsetHashId() {
    this.hashId = null;
  }

  /** Returns true if field hashId is set (has been assigned a value) and false otherwise */
  public boolean isSetHashId() {
    return this.hashId != null;
  }

  public void setHashIdIsSet(boolean value) {
    if (!value) {
      this.hashId = null;
    }
  }

  public boolean isSuccess() {
    return this.success;
  }

  public PlayInfo setSuccess(boolean success) {
    this.success = success;
    setSuccessIsSet(true);
    return this;
  }

  public void unsetSuccess() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  /** Returns true if field success is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess() {
    return EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  public void setSuccessIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
  }

  public String getMsg() {
    return this.msg;
  }

  public PlayInfo setMsg(String msg) {
    this.msg = msg;
    return this;
  }

  public void unsetMsg() {
    this.msg = null;
  }

  /** Returns true if field msg is set (has been assigned a value) and false otherwise */
  public boolean isSetMsg() {
    return this.msg != null;
  }

  public void setMsgIsSet(boolean value) {
    if (!value) {
      this.msg = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAYINFO_ID:
      if (value == null) {
        unsetPlayinfoId();
      } else {
        setPlayinfoId((Integer)value);
      }
      break;

    case HASH_ID:
      if (value == null) {
        unsetHashId();
      } else {
        setHashId((String)value);
      }
      break;

    case SUCCESS:
      if (value == null) {
        unsetSuccess();
      } else {
        setSuccess((Boolean)value);
      }
      break;

    case MSG:
      if (value == null) {
        unsetMsg();
      } else {
        setMsg((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAYINFO_ID:
      return Integer.valueOf(getPlayinfoId());

    case HASH_ID:
      return getHashId();

    case SUCCESS:
      return Boolean.valueOf(isSuccess());

    case MSG:
      return getMsg();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAYINFO_ID:
      return isSetPlayinfoId();
    case HASH_ID:
      return isSetHashId();
    case SUCCESS:
      return isSetSuccess();
    case MSG:
      return isSetMsg();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PlayInfo)
      return this.equals((PlayInfo)that);
    return false;
  }

  public boolean equals(PlayInfo that) {
    if (that == null)
      return false;

    boolean this_present_playinfoId = true;
    boolean that_present_playinfoId = true;
    if (this_present_playinfoId || that_present_playinfoId) {
      if (!(this_present_playinfoId && that_present_playinfoId))
        return false;
      if (this.playinfoId != that.playinfoId)
        return false;
    }

    boolean this_present_hashId = true && this.isSetHashId();
    boolean that_present_hashId = true && that.isSetHashId();
    if (this_present_hashId || that_present_hashId) {
      if (!(this_present_hashId && that_present_hashId))
        return false;
      if (!this.hashId.equals(that.hashId))
        return false;
    }

    boolean this_present_success = true;
    boolean that_present_success = true;
    if (this_present_success || that_present_success) {
      if (!(this_present_success && that_present_success))
        return false;
      if (this.success != that.success)
        return false;
    }

    boolean this_present_msg = true && this.isSetMsg();
    boolean that_present_msg = true && that.isSetMsg();
    if (this_present_msg || that_present_msg) {
      if (!(this_present_msg && that_present_msg))
        return false;
      if (!this.msg.equals(that.msg))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(PlayInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPlayinfoId()).compareTo(other.isSetPlayinfoId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayinfoId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playinfoId, other.playinfoId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHashId()).compareTo(other.isSetHashId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHashId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hashId, other.hashId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMsg()).compareTo(other.isSetMsg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMsg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.msg, other.msg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PlayInfo(");
    boolean first = true;

    sb.append("playinfoId:");
    sb.append(this.playinfoId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("hashId:");
    if (this.hashId == null) {
      sb.append("null");
    } else {
      sb.append(this.hashId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("success:");
    sb.append(this.success);
    first = false;
    if (!first) sb.append(", ");
    sb.append("msg:");
    if (this.msg == null) {
      sb.append("null");
    } else {
      sb.append(this.msg);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PlayInfoStandardSchemeFactory implements SchemeFactory {
    public PlayInfoStandardScheme getScheme() {
      return new PlayInfoStandardScheme();
    }
  }

  private static class PlayInfoStandardScheme extends StandardScheme<PlayInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PlayInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLAYINFO_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.playinfoId = iprot.readI32();
              struct.setPlayinfoIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HASH_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hashId = iprot.readString();
              struct.setHashIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SUCCESS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.success = iprot.readBool();
              struct.setSuccessIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.msg = iprot.readString();
              struct.setMsgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PlayInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PLAYINFO_ID_FIELD_DESC);
      oprot.writeI32(struct.playinfoId);
      oprot.writeFieldEnd();
      if (struct.hashId != null) {
        oprot.writeFieldBegin(HASH_ID_FIELD_DESC);
        oprot.writeString(struct.hashId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
      oprot.writeBool(struct.success);
      oprot.writeFieldEnd();
      if (struct.msg != null) {
        oprot.writeFieldBegin(MSG_FIELD_DESC);
        oprot.writeString(struct.msg);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PlayInfoTupleSchemeFactory implements SchemeFactory {
    public PlayInfoTupleScheme getScheme() {
      return new PlayInfoTupleScheme();
    }
  }

  private static class PlayInfoTupleScheme extends TupleScheme<PlayInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PlayInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPlayinfoId()) {
        optionals.set(0);
      }
      if (struct.isSetHashId()) {
        optionals.set(1);
      }
      if (struct.isSetSuccess()) {
        optionals.set(2);
      }
      if (struct.isSetMsg()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetPlayinfoId()) {
        oprot.writeI32(struct.playinfoId);
      }
      if (struct.isSetHashId()) {
        oprot.writeString(struct.hashId);
      }
      if (struct.isSetSuccess()) {
        oprot.writeBool(struct.success);
      }
      if (struct.isSetMsg()) {
        oprot.writeString(struct.msg);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PlayInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.playinfoId = iprot.readI32();
        struct.setPlayinfoIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.hashId = iprot.readString();
        struct.setHashIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.success = iprot.readBool();
        struct.setSuccessIsSet(true);
      }
      if (incoming.get(3)) {
        struct.msg = iprot.readString();
        struct.setMsgIsSet(true);
      }
    }
  }

}

